import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "@/components/sidebar/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className='flex flex-row w-full min-h-screen'>
          <Sidebar />
          <div className='w-full h-screen overflow-y-auto p-4 flex flex-col items-center'>
          {children}
          </div>
        </main>
      </body>
    </html>
  );
}
